import { DM_Serif_Display, DM_Serif_Text } from "next/font/google";
import "./globals.css";

const display = DM_Serif_Display({
  weight: '400',
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
});

const text = DM_Serif_Text({
  weight: '400',
  subsets: ["latin"],
  variable: "--font-text",
  display: "swap",
});

export const metadata = {
  title: "LCCMR Demo App",
  description: "Generated by create next app",
};

//antialiased class is used to enable font smoothing
// and improve the appearance of text on the screen
// https://tailwindcss.com/docs/font-smoothing

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${display.variable} ${text.variable} antialiased`}>
      <body
      >
        {children}
      </body>
    </html>
  );
}
